name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type-check
        run: npm run type-check

      - name: Run ESLint and generate report
        run: |
          mkdir -p reports
          npx eslint 'src/**/*.{ts,tsx,js,jsx}' -f html -o reports/eslint-report.html
          npx eslint 'src/**/*.{ts,tsx,js,jsx}' --max-warnings=0

      - name: Run Prettier check and generate report
        run: |
          mkdir -p reports  # Aseguramos que el directorio "reports" esté presente
          npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,scss,md}" --loglevel=debug
          npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,scss,md}" > reports/prettier-report.txt || true
          cat reports/prettier-report.txt  # Mostrar el reporte de Prettier en los logs

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: reports/eslint-report.html

      - name: Upload Prettier report
        uses: actions/upload-artifact@v4
        with:
          name: prettier-report
          path: reports/prettier-report.txt